=== nueschs/SparkLisa/target/classes/xml/sensor_topology.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://mcs.unibnf.ch/sparklisa/sensor-topology"
  xmlns:tns="http://mcs.unibnf.ch/sparklisa/sensor-topology"
  elementFormDefault="qualified">

  <complexType name="nodeType">
    <sequence>
      <element name="neighbours">
        <complexType>
          <sequence>
            <element name="neighbour" type="IDREF" minOccurs="0"
              maxOccurs="4" />
          </sequence>
        </complexType>
        <unique name="neighbourUnique">
          <selector xpath="neighbour" />
          <field xpath="." />
        </unique>
      </element>
    </sequence>
    <attribute name="nodeId" type="ID" use="required" />
  </complexType>

  <complexType name="basestationType">
    <sequence>
      <element name="managedNodes" minOccurs="1" maxOccurs="1">
        <complexType>
          <sequence>
            <element name="node" type="IDREF" minOccurs="0"
              maxOccurs="unbounded" />
          </sequence>
        </complexType>
      </element>
    </sequence>
    <attribute name="stationId" type="ID" use="required" />
  </complexType>


  <element name="topology">
    <complexType>
      <sequence>
        <element name="nodes">
          <complexType>
            <sequence>
              <element name="node" type="tns:nodeType"
                minOccurs="0" maxOccurs="unbounded" />
            </sequence>
          </complexType>
        </element>

        <element name="basestations">
          <complexType>
            <sequence>
              <element name="basestation" type="tns:basestationType"
                minOccurs="0" maxOccurs="unbounded" />
            </sequence>
          </complexType>
        </element>
      </sequence>
    </complexType>
  </element>
</schema>

=== nueschs/SparkLisa/target/classes/xml/simple_topology.xml
<?xml version="1.0" encoding="UTF-8"?>
<topology xmlns="http://mcs.unibnf.ch/sparklisa/sensor-topology"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://mcs.unibnf.ch/sparklisa/sensor-topology sensor_topology.xsd ">
	<nodes>	
		<node nodeId="node1">
			<neighbours>
				<neighbour>node2</neighbour>
			</neighbours>
		</node>
		<node nodeId="node2">
			<neighbours>
				<neighbour>node1</neighbour>
				<neighbour>node6</neighbour>
			</neighbours>
		</node>
		<node nodeId="node3">
			<neighbours>
				<neighbour>node4</neighbour>
			</neighbours>
		</node>
		<node nodeId="node4">
			<neighbours>
				<neighbour>node3</neighbour>
				<neighbour>node8</neighbour>
			</neighbours>
		</node>
		<node nodeId="node5">
			<neighbours>
				<neighbour>node6</neighbour>
			</neighbours>
		</node>
		<node nodeId="node6">
			<neighbours>
				<neighbour>node2</neighbour>
				<neighbour>node5</neighbour>
				<neighbour>node7</neighbour>
				<neighbour>node10</neighbour>
			</neighbours>
		</node>
		<node nodeId="node7">
			<neighbours>
				<neighbour>node6</neighbour>
				<neighbour>node8</neighbour>
			</neighbours>
		</node>
		<node nodeId="node8">
			<neighbours>
				<neighbour>node4</neighbour>
				<neighbour>node7</neighbour>
			</neighbours>
		</node>
		<node nodeId="node9">
			<neighbours>
				<neighbour>node13</neighbour>
			</neighbours>
		</node>
		<node nodeId="node10">
			<neighbours>
				<neighbour>node6</neighbour>
				<neighbour>node11</neighbour>
			</neighbours>
		</node>
		<node nodeId="node11">
			<neighbours>
				<neighbour>node10</neighbour>
				<neighbour>node12</neighbour>
				<neighbour>node15</neighbour>
			</neighbours>
		</node>
		<node nodeId="node12">
			<neighbours>
				<neighbour>node11</neighbour>
				<neighbour>node16</neighbour>
			</neighbours>
		</node>
		<node nodeId="node13">
			<neighbours>
				<neighbour>node9</neighbour>
				<neighbour>node14</neighbour>
			</neighbours>
		</node>
		<node nodeId="node14">
			<neighbours>
				<neighbour>node13</neighbour>
				<neighbour>node15</neighbour>
			</neighbours>
		</node>
		<node nodeId="node15">
			<neighbours>
				<neighbour>node11</neighbour>
				<neighbour>node14</neighbour>
			</neighbours>
		</node>
		<node nodeId="node16">
			<neighbours>
				<neighbour>node12</neighbour>
			</neighbours>
		</node>
	</nodes>
	
	<basestations>
		<basestation stationId="station1">
			<managedNodes>
				<node>node1</node>
				<node>node2</node>
				<node>node5</node>
				<node>node6</node>
			</managedNodes>
		</basestation>
		<basestation stationId="station2">
			<managedNodes>
				<node>node3</node>
				<node>node4</node>
				<node>node7</node>
				<node>node8</node>
			</managedNodes>
		</basestation>
		<basestation stationId="station3">
			<managedNodes>
				<node>node9</node>
				<node>node10</node>
				<node>node13</node>
				<node>node14</node>
			</managedNodes>
		</basestation>
		<basestation stationId="station4">
			<managedNodes>
				<node>node11</node>
				<node>node12</node>
				<node>node15</node>
				<node>node16</node>
			</managedNodes>
		</basestation>
	</basestations>	
</topology>
