=== nueschs/SparkLisa/src/main/resources/xml/sensor_topology.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://mcs.unibnf.ch/sparklisa/sensor-topology"
    xmlns:tns="http://mcs.unibnf.ch/sparklisa/sensor-topology"
    xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" elementFormDefault="qualified" jaxb:version="2.1">

    <complexType name="nodeType">
        <sequence>
            <element name="neighbour" type="IDREF" minOccurs="0"
                maxOccurs="4">
                <annotation>
                    <appinfo>
                        <jaxb:property>
                            <jaxb:baseType
                                name="NodeType" />
                        </jaxb:property>
                    </appinfo>
                </annotation>
            </element>
        </sequence>
        <attribute name="nodeId" type="ID" use="required" />
    </complexType>

    <complexType name="basestationType">
        <sequence>
            <element name="node" type="IDREF" minOccurs="0"
                maxOccurs="unbounded">
                <annotation>
                    <appinfo>
                        <jaxb:property>
                            <jaxb:baseType
                                name="NodeType" />
                        </jaxb:property>
                    </appinfo>
                </annotation>
            </element>
        </sequence>
        <attribute name="stationId" type="ID" use="required" />
    </complexType>


    <element name="topology">
        <complexType>
            <sequence>
                <element name="node" type="tns:nodeType"
                    minOccurs="0" maxOccurs="unbounded">
                    <unique name="neighbourUnique">
                        <selector xpath="neighbour" />
                        <field xpath="." />
                    </unique>
                </element>

                <element name="basestation" type="tns:basestationType"
                    minOccurs="0" maxOccurs="unbounded" />
            </sequence>
        </complexType>
    </element>
</schema>

=== nueschs/SparkLisa/src/main/resources/xml/simple_topology.xml
<?xml version="1.0" encoding="UTF-8"?>
<topology xmlns="http://mcs.unibnf.ch/sparklisa/sensor-topology"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://mcs.unibnf.ch/sparklisa/sensor-topology sensor_topology.xsd ">
    <node nodeId="node1">
        <neighbour>node2</neighbour>
    </node>
    <node nodeId="node2">
        <neighbour>node1</neighbour>
        <neighbour>node6</neighbour>
    </node>
    <node nodeId="node3">
        <neighbour>node4</neighbour>
    </node>
    <node nodeId="node4">
        <neighbour>node3</neighbour>
        <neighbour>node8</neighbour>
    </node>
    <node nodeId="node5">
        <neighbour>node6</neighbour>
    </node>
    <node nodeId="node6">
        <neighbour>node2</neighbour>
        <neighbour>node5</neighbour>
        <neighbour>node7</neighbour>
        <neighbour>node10</neighbour>
    </node>
    <node nodeId="node7">
        <neighbour>node6</neighbour>
        <neighbour>node8</neighbour>
    </node>
    <node nodeId="node8">
        <neighbour>node4</neighbour>
        <neighbour>node7</neighbour>
    </node>
    <node nodeId="node9">
        <neighbour>node13</neighbour>
    </node>
    <node nodeId="node10">
        <neighbour>node6</neighbour>
        <neighbour>node11</neighbour>
    </node>
    <node nodeId="node11">
        <neighbour>node10</neighbour>
        <neighbour>node12</neighbour>
        <neighbour>node15</neighbour>
    </node>
    <node nodeId="node12">
        <neighbour>node11</neighbour>
        <neighbour>node16</neighbour>
    </node>
    <node nodeId="node13">
        <neighbour>node9</neighbour>
        <neighbour>node14</neighbour>
    </node>
    <node nodeId="node14">
        <neighbour>node13</neighbour>
        <neighbour>node15</neighbour>
    </node>
    <node nodeId="node15">
        <neighbour>node11</neighbour>
        <neighbour>node14</neighbour>
    </node>
    <node nodeId="node16">
        <neighbour>node12</neighbour>
    </node>

    <basestation stationId="station1">
        <node>node1</node>
        <node>node2</node>
        <node>node5</node>
        <node>node6</node>
    </basestation>
    <basestation stationId="station2">
        <node>node3</node>
        <node>node4</node>
        <node>node7</node>
        <node>node8</node>
    </basestation>
    <basestation stationId="station3">
        <node>node9</node>
        <node>node10</node>
        <node>node13</node>
        <node>node14</node>
    </basestation>
    <basestation stationId="station4">
        <node>node11</node>
        <node>node12</node>
        <node>node15</node>
        <node>node16</node>
    </basestation>
</topology>
